default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1

development:
  <<: *default
  database: testapp_development
  pool: 20
  username: root
  password:

test:
  <<: *default
  database: testapp_test
  pool: 50
  username: root
  password:
  reconnect: true
  variables:
    sql_mode: TRADITIONAL
